### ISSUE TITLE
Application is broken on Safari

### ISSUE THREAD

**Issue by jeremyvergnas** [SpoonX/swan-example-client#34]
Seems like the SWAN example doesn't work on Safari
![screen shot 2016-09-06 at 13 23 57](https://cloud.githubusercontent.com/assets/6155967/18272382/d69ab1b2-7437-11e6-9d23-743d89dbc339.png)

**Note:**
@doktordirk:
safari windows gives: Unhandled rejection Error: HttpClient requires a Fetch API implementation, but the current environment doesn't support it. You may need to load a polyfill such as https://github.com/github/fetch.

@RWOverdijk:
Perhaps if we import the fetch client it's fixed

**Comment by doktordirk** [comment]
works for me https://github.com/SpoonX/swan-example-client/pull/35

**Comment by doktordirk** [comment]
http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/3

**Comment by VMBindraban** [comment]
@jeremyvergnas Does it work now?

**Comment by jeremyvergnas** [comment]
Last time I tried, it did...

**Comment by VMBindraban** [comment]
Can you close the issue then? :)
